### PR TITLE
Added an extra line to story

### PR DESCRIPTION
**Pull request by def08**
Any feedback?

### CODE REVIEW

**Review by dotainion — CHANGES_REQUESTED** [review]
remove your line of code and add to a new file name .. note of your chioice

**Review by BrendonLewis — COMMENTED** [review]
Looks good to me.

**Comment by def08** [comment]
Code moved, please review again.

**Review by johnnyboy190 — APPROVED** [review]
code is working fine

**Review by BrendonLewis — APPROVED** [review]

**Pull request merged**
